### ISSUE TITLE
Committed to this repo, review here.

### ISSUE THREAD

**Issue by bnb** [anvilresearch/connect-docs#4]
I accidentally committed updates to the overview file to the main repo; I thought I was in my fork, but it turns out I wasn't. Here is my commit: https://github.com/anvilresearch/connect-docs/commit/eefc9d4d3889c15999e4cce38110f43888d48058

Let me know if we need to roll this back or I need to update it further.

**Comment by vsimonian** [comment]
I don't seem to see much of an issue; looks like a great contribution! Any feedback, @christiansmith? Looks like this has been around for a while now.
